{% set version = '1.3-1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rjsonio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RJSONIO_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RJSONIO/RJSONIO_{{ version }}.tar.gz
  sha256: 550e18f7c04186376d67747b8258f529d205bfc929da9194fe45ec384e092d7e

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('RJSONIO')"           # [not win]
    - "\"%R%\" -e \"library('RJSONIO')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RJSONIO
  license: BSD_3_clause
  summary: This is a package that allows conversion to and from  data in Javascript object notation
    (JSON) format. This allows R objects to be inserted into Javascript/ECMAScript/ActionScript
    code and allows R programmers to read and convert JSON content to R objects. This
    is an alternative to rjson package. Originally, that was too slow for converting
    large R objects to JSON and was not extensible.  rjson's performance is now similar
    to this package, and perhaps slightly faster in some cases. This package uses methods
    and is readily extensible by defining methods for different classes,  vectorized
    operations, and C code and callbacks to R functions for deserializing JSON objects
    to R.  The two packages intentionally share the same basic interface. This package
    (RJSONIO) has many additional options to allow customizing the generation and processing
    of JSON content. This package uses libjson rather than implementing yet another
    JSON parser. The aim is to support other general projects by building on their work,
    providing feedback and benefit from their ongoing development.
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1

# Package: RJSONIO
# Version: 1.3-1.2
# Title: Serialize R Objects to JSON, JavaScript Object Notation
# Description: This is a package that allows conversion to and from  data in Javascript object notation (JSON) format. This allows R objects to be inserted into Javascript/ECMAScript/ActionScript code and allows R programmers to read and convert JSON content to R objects. This is an alternative to rjson package. Originally, that was too slow for converting large R objects to JSON and was not extensible.  rjson's performance is now similar to this package, and perhaps slightly faster in some cases. This package uses methods and is readily extensible by defining methods for different classes,  vectorized operations, and C code and callbacks to R functions for deserializing JSON objects to R.  The two packages intentionally share the same basic interface. This package (RJSONIO) has many additional options to allow customizing the generation and processing of JSON content. This package uses libjson rather than implementing yet another JSON parser. The aim is to support other general projects by building on their work, providing feedback and benefit from their ongoing development.
# Note: See http://www.json.org/JSON_checker/test.zip for tests. We now use code from the libjson project (http://libjson.sourceforge.net).
# License: BSD_3_clause + file LICENSE
# Imports: methods
# Authors@R: c(person("Duncan", "Temple Lang", role = c("aut", "cre"), email = "duncan@r-project.org", comment = c(ORCID = "0000-0003-0159-1546")), person("Jonathan", "Wallace", role = "aut", comment = "aka ninja9578, author of included libjson sources"))
# Collate: readJSON.R asVars.R isValid.R json.R simpleHandler.R stream.R
# Biarch: true
# NeedsCompilation: yes
# Packaged: 2019-06-04 09:49:10 UTC; ripley
# Author: Duncan Temple Lang [aut, cre] (<https://orcid.org/0000-0003-0159-1546>), Jonathan Wallace [aut] (aka ninja9578, author of included libjson sources)
# Maintainer: ORPHANED
# X-CRAN-Original-Maintainer: Duncan Temple Lang <duncan@r-project.org>
# X-CRAN-Comment: Orphaned and corrected on 2018-11-12, after 4 years of no corrections.
# Repository: CRAN
# Date/Publication: 2019-06-04 10:19:07 UTC
