appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: s7EhqRmXtXKpC9rezObAvXOJizHLVWA6daEVGjtnnWVQKvRFbejv1x+rCiif+KDFTyAP8gQ9VQObloTDsA6w3y2E18iZwgQQctITbdGYiuW17XIIVTiHujkqEmvg0vMU2LpP25RjlFpACv+mqomYR3PARcshJTo66SjtfKGqxB38yqmYY2JMtlpeUskGXUEc9O/mYmYjnr13NLN8ftuQGwDLzTXolelcCoUMC2mZPj5FYVdcKnaTWdC7wsFkzsr7uxyPuAOdCyVpOgU/nfAqAgnL2+IE77DudCpXA3IPu81NwCtO7BDHeUEoe/CSXvQmrkc+/RifbgxA+PfWBazNR9WwUFJjNfErcGrzUG7/KdMD0T730oEJKAXVo6Z2V1k0ow9A7bXArwV/ev70/oVoo+cNM3gL1kqUl93UzgHsBQpUIVw4B4ZGE5z9JxObWVfC8bDZ5jM5Pypu1mutcq7Q9b5vWw/IY2CahpTWNbdv9DKJvrJrex1zuFmlhdnSJ2EKrRIEAcel8F1DI2+c55pgy/cybaAZhq4dnRlR6iWwiIaugCyx6Jl4fk32EiTvYgkM9ZUIiIOzN7Sh832ifw315Tnb6KsPgEWoVSHR7i0Re1VuchztdRoGJ6FMEARDHXaenwlFkuBH4hIw6vE2cII7ReumzPEHb/6q8nymVLJqw5s=
